secret verification

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -6,6 +6,14 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+      - name: Verify secret
+        run: |
+          if [ -z "${{ secrets.TESTS_ACCESS_TOKEN }}" ]; then
+            echo "ERROR: Token is not set!"
+            exit 1
+          else
+            echo "Token is available (first 3 chars: ${ secrets.TESTS_ACCESS_TOKEN:0:3}...)"
+          fi
       
       # Секретно загружаем тесты
       - name: Download hidden tests
